# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/RDF-Query-Client/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires
		"Test::More 0.61" ;
	:recommends
		"HTTP::LRDD" ;
	:requires
		"Carp 0" ,
		"HTTP::Request 0" ,
		"LWP::UserAgent 0" ,
		"RDF::Trine 0.133" ,
		"Scalar::Util 0" ,
		"URI::Escape 0" ,
		"namespace::clean 0.20" ,
		"authority::shared 0" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/RDF/Query/Client.pm" .

